### ISSUE TITLE
<a> child of <a>

### ISSUE THREAD

**Issue by justinwhall** [staticfuse/create-gatsby-theme-publisher#3]
Likely due to the `logo.js` shadowing component.

![image](https://user-images.githubusercontent.com/877404/67148161-7aeeeb00-f259-11e9-89af-c75c4843ce81.png)

![image](https://user-images.githubusercontent.com/877404/67148171-95c15f80-f259-11e9-882b-ed8909c66f22.png)

**Comment by scottopolis** [comment]
Should be fixed in https://github.com/staticfuse/create-gatsby-theme-publisher/commit/5e9c3662511b43ef7ac2c1571737f2bc02dfb571
