### ISSUE TITLE
An unexpected error occurred: "expected hoisted manifest for \"@staticfuse/gatsby-theme-publisher#gatsby#gatsby-link#gatsby\"".

### ISSUE THREAD

**Issue by v9ai** [staticfuse/create-gatsby-theme-publisher#4]
Hello, I've tried to install the theme on my Ubuntu 18 and did get this error from below :point_down: 

Did you encounter this error as well?
***

![Peek 2019-10-23 13-26](https://user-images.githubusercontent.com/1477453/67384032-10abb280-f599-11e9-816b-7d25f3dbfa00.gif)

**Comment by v9ai** [comment]
This is my node/ npm version:

![image](https://user-images.githubusercontent.com/1477453/67384141-48b2f580-f599-11e9-976f-2e58bbbb63fa.png)

**Comment by v9ai** [comment]
Maybe there should be a `.nvmrc` config file?

**Comment by v9ai** [comment]
Fun fact, this is not happening in `/demo` folder of `gatsby-theme-publisher`:
https://github.com/staticfuse/gatsby-theme-publisher/tree/master/demo

**Comment by scottopolis** [comment]
Hi, I'm getting this error on node 10.16.3 as well, and 12.9.1 also has a different error. Yay!

Removing the yarn.lock file and then running yarn again seems to resolve the issue. We will dig into this further and get a fix, thanks for the report.

**Comment by v9ai** [comment]
Thanks @scottopolis

**Comment by scottopolis** [comment]
@justinwhall can you look at this one? Deleting yarn.lock is a temporary fix, but we should find the underlying issue.

**Comment by scottopolis** [comment]
The new yarn.lock file fixed this issue.

**Comment by jamesdbruner** [comment]
Deleting your `yarn.lock` is not a solution and should not be done without understanding the repercussions of doing so.
