### ISSUE TITLE
error Found incompatible module

### ISSUE THREAD

**Issue by zakirsajib** [staticfuse/create-gatsby-theme-publisher#5]
error @staticfuse/gatsby-theme-publisher@0.10.10: The engine "node" is incompatible with this module. Expected version ">=10.16". Got "10.15.3"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by justinwhall** [comment]
Hey @zakirsajib - This means your node version does not meet the minimum required. Looks like you are using 10.15.3 and this requires 10.6 or later. 

I'd recommend [NVM](https://github.com/nvm-sh/nvm) if you need to switch between Node versions.
